# Generated by Django 4.0.5 on 2022-06-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shout',
            options={'ordering': ['-id']},
        ),
    ]
