# Generated by Django 4.0.5 on 2022-06-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0004_shoutlike_shout_likes_shout_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shouts.shout'),
        ),
    ]
