# Generated by Django 4.0.5 on 2022-06-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0005_shout_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='thread_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_parent_shout', to='shouts.shout'),
        ),
        migrations.AlterField(
            model_name='shout',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_shout', to='shouts.shout'),
        ),
    ]
