# Generated by Django 4.0.5 on 2022-06-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0008_remove_shout_thread_child_shout_thread_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='thread_child',
            field=models.ManyToManyField(to='shouts.shout'),
        ),
    ]
