# Generated by Django 4.0.5 on 2022-07-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followers_profile_timestamp_profile_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
