# Generated by Django 4.0.5 on 2022-07-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(default='defaultname', max_length=30),
            preserve_default=False,
        ),
    ]
